version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_innovacion
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TuPasswordSegura123!
    ports:
      - "11477:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'TuPasswordSegura123!' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - red_innovacion

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db_init_innovacion
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db:/db
    entrypoint: [ "/bin/bash", "/db/init.sh" ]
    networks:
      - red_innovacion

  api:
    build:
      context: ./api_innovacion
      dockerfile: Dockerfile
    container_name: api_innovacion_v1
    ports:
      - "8124:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConexionSQL=Server=db,1433;Database=innovacion_curricular;User Id=sa;Password=TuPasswordSegura123!;TrustServerCertificate=True;Encrypt=False
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=innovacion_curricular;User Id=sa;Password=TuPasswordSegura123!;TrustServerCertificate=True;Encrypt=False
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - red_innovacion

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front_innovacion_v1
    ports:
      - "8125:80"
    depends_on:
      - api
    networks:
      - red_innovacion

networks:
  red_innovacion:
    driver: bridge